### ISSUE TITLE
Add an option to exclude files and folders from index by mask

### ISSUE THREAD

**Issue by voronkovich** [mkusher/padawan.php#12]

**Comment by mkusher** [comment]
@voronkovich why do you need such functionality?

**Comment by voronkovich** [comment]
@mkusher, when I create an index for a Symfony project, padawan scans the `app/cache` directory.

**Comment by mkusher** [comment]
@voronkovich thanks, nice case

**Comment by voronkovich** [comment]
@mkusher, I think, you could add support for  `.gitignore` files, or another files with the same format.

**Comment by mkusher** [comment]
@voronkovich I'm thinking about creating project files, e.g. `.padawan-project.json` or `.padawan-project.yml` with the structure like:

``` yml
exclude:
 - "*/cache/*"
 - "*.cache"
plugins:
 - "mkusher/padawan-symfony"
```

have you any ideas about it?
