### ISSUE TITLE
Project file

### ISSUE THREAD

**Issue by mkusher** [mkusher/padawan.php#20]
# Proposal

Project file is a yaml(e.g. `.padawan.yml`) configuration for a project.
## Structure

``` yaml
php: 7
plugins:
    Mkusher\SymfonyPlugin:
    Someone\SomepackagePlugin:
        extra_option_for_somepackagePlugin: 1
exclude: ['app/bootstrap.php.cache', 'app/cache/*']
cache_dir: '.padawan'
```

here we have 3 sections:
1. `plugins` - plugins you want to be enabled for this project
2. `exclude` - files or folders you want to exclude from being indexed
3. `cache_dir` - folder for padawan.php cache for this project
4. `php` - version of php being used for running padawan. Could be 5 or 7. php5.\* will use nikic/PHP-Parser and 7 will use built-in AST builder.
## Editors' plugins

Before editors were looking for composer.json file, now they will have to look for `.padawan.yml` first and only then look for `composer.json`.
